export interface Case {
  _id: string; // MongoDB ID
  Case_Number: string;
  Police_Station: string;
  District: string;
  Investigating_Officer: string;
  Rank: string;
  Accused_Name: string;
  Gender: string;
  Age: number;
  Accused_Alias: string;
  Crime_Type: string;
  Sections_at_FIR: string;
  Sections_at_Chargesheet: string;
  Sections_at_Final: string;
  Nature_of_Offence: string;
  PP_Name: string;
  Court_Name: string;
  Judge_Name: string;
  Date_of_Registration: string;
  Date_of_Chargesheet: string;
  Date_of_Trial_Start: string;
  Date_of_Judgement: string;
  Result: "Convicted" | "Acquitted" | string;
  Sentence_Type: string;
  Duration_of_Trial_days: number;
  CCTNS_Case_ID: string;
  CIS_Case_Ref: string;
  Prosecution_File_No: string;
  Data_Source: string;
  Sync_Status: string;
  Remarks: string;
  Term_Unit: string;
  Place_of_Occurrence: string;
  Complainant_Informant: string;
  GD_Reference: string;
  Accused_Details: string;
  Delay_Reason: string;
  FIR_Contents: string;
  Action_Taken: string;
  Dispatch_to_Court: string;
  Visit_to_Place_of_Occurrence: string;
  generated_judgment?: string;
}
